server:
#  port: 8080
  port: 0

#debug: true
logging:
  level:
    org:
      springframework:
        web: debug
      hibernate: error
    root: warn

spring:
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/ecare
    username: spring
    password: Po=V+|EBR^
  sql:
    init:
      # https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
#      mode: always
#      continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
    # https://stackoverflow.com/a/70776979/2879364
    defer-datasource-initialization: true
  application:
    name: ecare-tariff
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  interface:
    preferIpAddress: true
